export const TITLE_LIST_REQUEST = 'TITLE_LIST_REQUEST'
export const TITLE_LIST_SUCCESS = 'TITLE_LIST_SUCCESS'
export const TITLE_LIST_FAIL = 'TITLE_LIST_FAIL'

export const SENTENCE_DELETE_REQUEST = 'SENTENCE_DELETE_REQUEST'
export const SENTENCE_DELETE_SUCCESS = 'SENTENCE_DELETE_SUCCESS'
export const SENTENCE_DELETE_FAIL = 'SENTENCE_DELETE_FAIL'

export const SENTENCE_DETAILS_REQUEST = 'SENTENCE_DETAILS_REQUEST'
export const SENTENCE_DETAILS_SUCCESS = 'SENTENCE_DETAILS_SUCCESS'
export const SENTENCE_DETAILS_FAIL = 'SENTENCE_DETAILS_FAIL'
